sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  - npm i -g npm@^2.0.0
install:
  - npm install -g typescript
  - npm install
before_script:
  - npm prune
#  - curl -Lo travis_after_all.py https://git.io/vLSON
script:
  - npm run compile
  - npm run test-ci
after_success:
#  - python travis_after_all.py
  - npm run semantic-release
  - npm run coverage-publish
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"