sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_install:
  - cd buildtask\OwaspZapScan
  - npm i -g npm@^2.0.0
install:
  - npm install -g typescript
before_script:
script:
  - npm run build
after_success:
  - npm run semantic-release  
branches:
  except:
    - /^v\d+\.\d+\.\d+$/